name: crypto_benefit
description: Crypto.com benefit calculator
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # iOS Icon
  cupertino_icons: ^1.0.0

  # Intl (String format and internationalization)
  intl: ^0.16.1

  # Moor (database)
  moor: ^3.3.1
  encrypted_moor:
    git:
     url: https://github.com/simolus3/moor.git
     path: extras/encryption
    
  # Sqlite 3 (latest versions)
  sqlite3_flutter_libs: ^0.2.0 

  # RxDart, more flexibility arround streams
  rxdart: ^0.24.1

  # GetIt (dependency injection)
  get_it: ^5.0.1

  # MobX (ease the state managment)
  mobx: ^1.2.1+3
  flutter_mobx: ^1.1.0+2

  # App preferences for both iOS and Android
  shared_preferences: ^0.5.12+2

  # Read CSV content
  csv: ^4.0.3

  # Path provider and path (Acess file on the system)
  path_provider: ^1.6.21
  path: ^1.7.0

  # Let the user pick a document (in our case import csv files)
  flutter_document_picker: ^4.0.0

  # Better UI grid view
  flutter_staggered_grid_view: ^0.3.2

  # Shimmer (for some loading views)
  shimmer: ^1.1.2

  # Selectable container (for better selection view to create stats)
  selectable_container: ^0.1.4

  # Smooth expandable container
  expandable: ^4.1.4
  
dev_dependencies:
  moor_generator: ^3.4.0
  mobx_codegen: ^1.1.1+1
  build_runner: ^1.10.3
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true